language: node_js
node_js:
  - "5.8"

before_script:
  #Install app depdendencies
  - npm install -g webpack
  - npm install -g karma-cli
  - npm install -g jasmine
  #Configure visual frame buffer for browser testing
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

